# Generated by Django 4.1.13 on 2025-03-13 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_populate_account_balances'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='icon',
            field=models.CharField(blank=True, default='💰', max_length=10, null=True),
        ),
    ]
