# Generated by Django 4.1.13 on 2025-03-11 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_plaiditems_account_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='plaiditem',
            name='cursor',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
