# Generated by Django 4.1.13 on 2025-03-14 20:48

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_update_reconciled_balances'),
    ]

    operations = [
        migrations.CreateModel(
            name='Saving',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('account', models.OneToOneField(limit_choices_to={'type': 'Goal'}, on_delete=django.db.models.deletion.CASCADE, related_name='saving', to='accounts.account')),
                ('contributing_accounts', models.ManyToManyField(blank=True, limit_choices_to={'type__in': ['Asset', 'Liability']}, related_name='contributes_to', to='accounts.account')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='savings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
