# Generated by Django 4.1.13 on 2025-03-21 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_saving'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='merchant',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
